version: '3.5'

services:
  lumen-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    depends_on:
      - mysql-db
    ports:
      - 8000:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
    env_file:
      - ./.env
    networks:
      backend:
        aliases:
          - app

  mysql-db:
    image: mysql:5.7
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - mysql-db

  composer:
      image: 3kezoh/composer:php-5.6
      volumes:
        - .:/app
      working_dir: /app
      command: composer install

networks:
  backend:
    name: backend-network